name: CI
on: [push, pull_request]
jobs:
  build:
    env:
      BUNDLE_GEMFILE: Gemfile
    runs-on: ${{ matrix.os }}-latest
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu, macos, macos-13]
        ruby-version: ['3.4']
    steps:
      - uses: actions/checkout@v3
      - name: Install libcurl header (Linux only)
        if: matrix.os == 'ubuntu'
        run: sudo apt update && sudo apt install -y --no-install-recommends libcurl4-openssl-dev
      - name: Set up Ruby ${{ matrix.ruby-version }}
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}
          bundler-cache: true
      - name: Run tests
        run: |
          bundle exec rake
      - name: Print libcurl version
        run: |
          bundle exec ruby -Ilib -e "require 'ethon'; puts Ethon::Curl.version"
